--- #YAML:1.0
name:                Catalyst-Plugin-Session
version:             0.18
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Catalyst:                      5.49
    Digest:                        0
    File::Spec:                    0
    File::Temp:                    0
    Object::Signature:             0
    Test::Deep:                    0
    Test::Exception:               0
    Test::MockObject:              1.01
    Test::More:                    0
    Tie::RefHash:                  1.34
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
