# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Session
version:      0.06
version_from: lib/Catalyst/Plugin/Session.pm
installdirs:  site
requires:
    Catalyst:                      5.49
    Digest:                        0
    File::Spec:                    0
    File::Temp:                    0
    Object::Signature:             0
    Test::Deep:                    0
    Test::Exception:               0
    Test::MockObject:              1.01
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
