---
abstract: 'Generic Session plugin - ties together server side storage and client side state required to maintain session data.'
author:
  - 'Andy Grundman'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.71001
  Digest: 0
  File::Spec: 0
  File::Temp: 0
  MRO::Compat: 0
  Moose: 0.76
  MooseX::Emulate::Class::Accessor::Fast: 0.00801
  Object::Signature: 0
  Test::More: 0
  Tie::RefHash: 1.34
  namespace::clean: 0.10
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-Session/0.00/trunk/
version: 0.30
